### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Horange321** [crdroidandroid/android_packages_modules_Virtualization-old#1]
While building latest crDroid 
error: failed to build archive: Unknown attribute kind (86) (Producer: 'LLVM17.0.4' Reader: 'LLVM 15.0.6-rust-dev')

How to solve the problem?

**Comment by Horange321** [comment]
Whole log:
//packages/modules/Virtualization/libs/libfdt:liblibfdt rustc src/lib.rs [apex10000]
FAILED: out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/android_arm64_armv8-a_rlib_rlib-std_apex10000/liblibfdt.rlib
OUT_DIR=$PWD/out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/android_arm64_armv8-a_rlib_rlib-std_apex10000/out ANDROID_RUST_VERSION=1.68.0 AR=prebuilts/clang/host/linux-x86/clang-r498229b/bin/llvm-ar prebuilts/rust/linux-x86/1.68.0/bin/rustc -C linker=build/soong/scripts/mkcratersp.py --emit link -o out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/android_arm64_armv8-a_rlib_rlib-std_apex10000/liblibfdt.rlib --emit dep-info=out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/android_arm64_armv8-a_rlib_rlib-std_apex10000/liblibfdt.rlib.d.raw packages/modules/Virtualization/libs/libfdt/src/lib.rs --extern libfdt_bindgen=out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt_bindgen/android_arm64_armv8-a_rlib_rlib-std_apex10000/liblibfdt_bindgen.rlib --extern core=out/soong/.intermediates/prebuilts/rust/libcore.rust_sysroot/android_arm64_armv8-a_rlib_apex10000/libcore.rust_sysroot.rlib -L out/soong/.intermediates/prebuilts/rust/libstd/android_arm64_armv8-a_rlib_apex10000/ -L out/soong/.intermediates/system/logging/liblog/liblog/android_arm64_armv8-a_shared/ -L out/soong/.intermediates/bionic/libc/libc/android_arm64_armv8-a_shared_current/ -L out/soong/.intermediates/bionic/libm/libm/android_arm64_armv8-a_shared_current/ -L out/soong/.intermediates/bionic/libdl/libdl/android_arm64_armv8-a_shared_current/ -L out/soong/.intermediates/prebuilts/rust/libcompiler_builtins.rust_sysroot/android_arm64_armv8-a_rlib_apex10000/ -L out/soong/.intermediates/prebuilts/rust/libcore.rust_sysroot/android_arm64_armv8-a_rlib_apex10000/ -L out/soong/.intermediates/prebuilts/rust/librustc_demangle.rust_sysroot/android_arm64_armv8-a_rlib_apex10000/ -L out/soong/.intermediates/prebuilts/rust/liblibc.rust_sysroot/android_arm64_armv8-a_rlib_apex10000/ -L out/soong/.intermediates/prebuilts/rust/libcfg_if.rust_sysroot/android_arm64_armv8-a_rlib_apex10000/ -L out/soong/.intermediates/prebuilts/rust/liballoc.rust_sysroot/android_arm64_armv8-a_rlib_apex10000/ -L out/soong/.intermediates/prebuilts/rust/libhashbrown.rust_sysroot/android_arm64_armv8-a_rlib_apex10000/ -L out/soong/.intermediates/prebuilts/rust/libunwind.rust_sysroot/android_arm64_armv8-a_rlib_apex10000/ -L out/soong/.intermediates/prebuilts/rust/libprofiler_builtins.rust_sysroot/android_arm64_armv8-a_rlib_apex10000/ -L out/soong/.intermediates/prebuilts/rust/libstd_detect.rust_sysroot/android_arm64_armv8-a_rlib_apex10000/ -L out/soong/.intermediates/prebuilts/rust/libpanic_abort.rust_sysroot/android_arm64_armv8-a_rlib_apex10000/ -L prebuilts/clang/host/linux-x86/clang-r498229b/lib/clang/17/lib/linux/ -L out/soong/.intermediates/external/dtc/libfdt/libfdt/android_arm64_armv8-a_static_apex10000/ -Z remap-cwd-prefix=. -C codegen-units=1 -C debuginfo=2 -C opt-level=3 -C relocation-model=pic -C overflow-checks=on -C force-unwind-tables=yes -C symbol-mangling-version=v0 --color always -A stable-features -Zdylib-lto   -C panic=abort -Z link-native-libraries=no -Z debug-info-for-profiling -A deprecated -D missing-docs -D warnings --edition=2021 -C metadata=liblibfdt -lstatic=fdt --crate-type=rlib --crate-name=libfdt --target=aarch64-linux-android --sysroot=/dev/null -Zallow-features="custom_inner_attributes,mixed_integer_ops" && grep "^out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/android_arm64_armv8-a_rlib_rlib-std_apex10000/liblibfdt.rlib:" out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/android_arm64_armv8-a_rlib_rlib-std_apex10000/liblibfdt.rlib.d.raw > out/soong/.intermediates/packages/modules/Virtualization/libs/libfdt/liblibfdt/android_arm64_armv8-a_rlib_rlib-std_apex10000/liblibfdt.rlib.d
error: failed to build archive: Unknown attribute kind (86) (Producer: 'LLVM17.0.4' Reader: 'LLVM 15.0.6-rust-dev')

**Comment by gwolf2u** [comment]
resync and build clean
